version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - sample/target/sample-1.0-SNAPSHOT-shaded.jar
    - appspec.yml
  discard-paths: yes